site_name: Meetup Openshift Startup
theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'blue'
nav:
    - Home: index.md
    - Prerequisites: prereqs.md
    - Lab1: lab1.md
    - Lab2: lab2.md
markdown_extensions:
    - attr_list
